//
//  PostClassicalReadingText.swift
//  World History
//
//  Created by Christopher Endress on 5/26/23.
//

import Foundation

struct PostClassicalReadingText {
  

    let postClassicalText = """
    The Early Middle Ages, sometimes traditionally labeled the “Dark Ages,” began with the fall of the Western Roman Empire in 476 CE. Modern historians, however, increasingly see this term as misleading. While certain regions of Europe did experience political fragmentation and a decline in some forms of urban life, the period was not simply one of darkness or decline. Instead, it was an era of transformation in which older Roman, Germanic, and Christian traditions blended, new cultures emerged, and important centers of learning and power developed both within and far beyond western Europe.

    Across what had once been the Western Roman Empire, a variety of Germanic kingdoms took shape and gradually stabilized. The Franks, Visigoths, Ostrogoths, Lombards, and others established realms that would evolve into many of the modern nations of Europe. Among these kingdoms, the Frankish realm rose to particular prominence under the Carolingian dynasty. Charlemagne, its most famous ruler, expanded his territories across much of Western and Central Europe and was crowned “Emperor of the Romans” by Pope Leo III in 800 CE. This act symbolized an attempt to link the legacy of the ancient Roman Empire with emerging medieval institutions and to present a vision of cooperation—though sometimes tense—between secular rulers and the Christian Church.

    Christianity, which had spread throughout the Roman Empire in earlier centuries, became even more deeply rooted across Europe during this era. Missionaries such as Saint Patrick in Ireland and Saint Augustine of Canterbury in England worked to convert local populations, often blending Christian teachings with existing cultural practices. The Church emerged as one of the most powerful institutions in Europe, influencing law, education, and everyday life. Monasteries, inhabited by monks and nuns, served as centers of spirituality and also as repositories of knowledge. Monastic communities preserved and copied ancient texts, including not only Christian writings but also works of classical philosophy, science, and literature. In a world where political structures were frequently unstable, the Church and its institutions provided continuity, social services, and a sense of shared identity for many communities.

    In the eastern Mediterranean, the Byzantine Empire—often called the Eastern Roman Empire—continued to thrive long after the fall of Rome in the West. Centered on its capital, Constantinople (modern-day Istanbul), Byzantium preserved and transformed Roman law, Greek language and culture, and Christian theology. Under Emperor Justinian I, Byzantine scholars compiled and refined centuries of Roman legal tradition into the Corpus Juris Civilis, a monumental legal code that later influenced many European legal systems. The empire became a vibrant crossroads of trade between Europe and Asia, and its artists and architects produced dazzling mosaics, domed churches such as Hagia Sophia, and rich religious iconography. At the same time, the Byzantine Empire faced ongoing military and religious challenges, including conflicts with neighboring powers and internal debates over theology and the use of religious images.

    Further east and south, a new religious and cultural force emerged in the 7th and 8th centuries: Islam. Following the life of the Prophet Muhammad in the Arabian Peninsula, Muslim communities expanded rapidly across the Middle East, North Africa, parts of Europe, and into Central and South Asia. Under the Abbasid Caliphate, especially with Baghdad as a major capital, the Islamic Golden Age blossomed. Scholars, artists, and scientists from diverse backgrounds—Arab, Persian, Central Asian, North African, and others—contributed to an extraordinary flourishing of knowledge. They translated and preserved Greek, Persian, and Indian texts; developed algebra and advanced astronomy; made important strides in medicine and optics; and produced influential works in philosophy and literature. The work of scholars such as Al-Khwarizmi, Al-Razi, Ibn Sina (Avicenna), and Al-Biruni played a crucial role in transmitting and expanding knowledge, much of which would later inform European intellectual life.

    The Early Middle Ages in northern Europe were also shaped by the seafaring peoples we now call the Vikings. Originating from Scandinavia, Norse sailors, traders, and warriors journeyed across the North Atlantic, the Baltic Sea, and deep into the rivers of Eastern Europe. They raided monasteries and towns, but they also engaged in trade, founded settlements, and established lasting connections. Viking explorers reached as far as Iceland, Greenland, and even briefly North America (Vinland). In regions such as England, Ireland, and parts of France, Viking settlements merged with local populations, influencing language, culture, and politics. In Eastern Europe, Norse groups known as the Rus’ played a role in forming early states in areas that would later become Russia and Ukraine, linking northern Europe to Byzantine and Islamic trade networks.

    During this era, Europe also saw the gradual emergence of feudal systems—a set of social and political relationships in which land was granted in exchange for military service, loyalty, and mutual obligations. While feudalism took different forms in different regions and never existed as a single uniform system, certain patterns were common. Kings or high-ranking lords granted land (fiefs) to vassals, who in return owed them service and support. At the base of this structure were peasants, many of whom were serfs tied to the land, working the fields in return for protection and the right to cultivate plots of their own. This web of obligations helped maintain order in a world where centralized states were often weak. Yet it also reinforced social hierarchies and limited mobility for many people, especially peasants and laborers, whose lives were shaped by local customs, seasons, and the demands of their lords.

    The High Middle Ages, roughly from the 11th to the 13th centuries, were marked by population growth and significant progress in agriculture, trade, and urban life across parts of Europe. As food supplies became more reliable, towns and cities expanded, and long-distance trade routes revived and intensified. Merchant and craft guilds formed to regulate quality and protect their members, while markets and fairs drew people from many regions. In this period, more distinct political identities began to take shape. Kingdoms such as England and France, as well as the loose confederation known as the Holy Roman Empire, consolidated power to varying degrees. At the same time, important polities far beyond Western Europe—including powerful states in West Africa like the Ghana and later Mali empires, as well as kingdoms and sultanates in India and Southeast Asia—were flourishing, connected through complex networks of trade and cultural exchange.

    One of the most dramatic and controversial developments of the High Middle Ages was the launching of the Crusades—military campaigns initiated by Latin Christian leaders, often with the support of the papacy, to capture or defend territories in the eastern Mediterranean, especially Jerusalem and other places of religious significance. From the late 11th century onward, multiple Crusades were fought, involving not only European knights but also local Christians, Muslims, and Jews who were deeply affected by these conflicts. The Crusades brought immense suffering, including massacres and persecution, yet they also intensified contact between different cultures. Goods, ideas, and technologies flowed between Europe, the Byzantine world, and the Muslim-ruled regions of the Middle East and North Africa. While the Crusades failed to establish lasting Latin Christian control over the Holy Land, they reshaped political boundaries, religious attitudes, and memories on all sides, leaving a complex legacy that is still discussed today.

    In religious life more broadly, the High Middle Ages witnessed the growing authority of the papacy and the emergence of influential movements for reform. New monastic orders such as the Cistercians sought a return to simpler, more austere forms of devotion, while mendicant orders like the Franciscans and Dominicans took vows of poverty and preached in cities, focusing on pastoral care and education. Monumental Gothic cathedrals, with their pointed arches, flying buttresses, and stained-glass windows, transformed urban skylines and became tangible expressions of religious devotion and communal pride. At the same time, universities emerged in places like Bologna, Paris, and Oxford, establishing institutions where scholars could study law, medicine, theology, and the liberal arts. These universities drew on classical texts, many of them preserved and commented upon by Muslim, Jewish, and Christian scholars, and became centers for debate, inquiry, and intellectual growth.

    Technological and agricultural innovations also shaped the High Middle Ages. The widespread adoption of the three-field system allowed farmers to rotate crops more efficiently, reducing soil exhaustion and increasing yields. The use of the heavy plow in northern Europe enabled deeper cultivation of heavy, clay-rich soils, expanding arable land. Harness improvements, such as the horse collar, allowed animals to pull heavier loads without injury, boosting productivity in both agriculture and transport. Windmills and watermills converted natural forces into mechanical power for grinding grain, sawing wood, and processing cloth. These innovations may seem modest compared to modern machines, but for people of the time they represented significant steps forward in the everyday struggle to produce food and goods, underpinning economic and demographic growth.

    The High Middle Ages were also a time of rich cultural and intellectual creativity across many regions. In the Muslim world, scholars such as Ibn Rushd (Averroes) in al-Andalus (Islamic Spain) engaged deeply with the works of Aristotle and other philosophers, writing commentaries that would later influence Jewish and Christian thinkers. Jewish philosophers like Maimonides made important contributions to theology and ethics, while in Christian Europe, thinkers such as Thomas Aquinas attempted to harmonize faith and reason, blending Christian doctrine with Aristotelian philosophy. Vernacular languages—such as early forms of French, Italian, and English—began to be used more widely in literature. In Italy, Dante Alighieri composed “The Divine Comedy,” a poetic journey through the afterlife that reflected both medieval theology and a growing interest in individual experience. Meanwhile, in other parts of the world, poets, historians, and artists were also producing major works, from Persian epic poetry to Chinese landscape painting, underscoring the global richness of post-classical culture.

    While many regions experienced growth and stability, others were transformed by dramatic conquests and shifting empires. In the 13th century, the Mongol Empire rose to extraordinary power under the leadership of Genghis Khan and his successors. At its height, it became the largest contiguous land empire in history, stretching from Eastern Europe to the Sea of Japan and from Siberia to parts of the Middle East and South Asia. The Mongols’ military campaigns were often devastating, resulting in the destruction of cities and loss of life. Yet once their rule was established, they also promoted trade and communication along the Silk Roads, facilitating the movement of goods, people, and ideas across Eurasia. Many historians describe this as a period of “Pax Mongolica,” during which merchants, missionaries, diplomats, and travelers such as Marco Polo moved with relative safety across vast distances, linking distant societies more closely than ever before.

    The High Middle Ages, then, were a time of remarkable transformation and growth, but also of conflict, inequality, and tension. The consolidation of states and churches, the expansion of cities and trade, and the development of new ideas all laid important foundations for the future. Yet these achievements existed alongside ongoing struggles: peasant uprisings, disputes between kings and popes, religious intolerance, and regional wars. By the late 13th and early 14th centuries, pressure on resources, changing climates, and political rivalries began to strain existing systems. The stage was quietly being set for the profound challenges and changes that would define the Late Middle Ages.

    The Late Middle Ages, roughly the 14th and 15th centuries, were marked by a series of crises and transformations that deeply affected societies across Europe, the Middle East, and beyond. One early catastrophe was the Great Famine of 1315–1317 in Europe, caused by poor weather and crop failures. Food shortages, rising prices, and malnutrition weakened populations and undermined confidence in traditional authorities. Soon after, the Black Death—a devastating pandemic of bubonic plague and related diseases—swept through Eurasia and North Africa in the mid-14th century. Originating in Central or East Asia and traveling along trade routes, the plague killed a huge portion of the population in many regions. The result was not only unimaginable human suffering but also long-term social, economic, and cultural consequences.

    In the aftermath of the Black Death, the structure of many societies began to shift. The drastic reduction in population created labor shortages, particularly in Europe, giving surviving workers more bargaining power in some places. Wages rose in certain regions, and some peasants were able to negotiate better terms or move to new lands. This challenged aspects of the feudal system and contributed to gradual changes in landholding patterns. At the same time, authorities often tried to freeze wages or restrict mobility, leading to tensions and unrest. In England, the Peasants’ Revolt of 1381 saw commoners challenge taxes and feudal obligations, while in France the Jacquerie uprising reflected anger at military devastation and social inequality. Similar tensions could be found elsewhere as ordinary people struggled to cope with economic disruption, war, and shifting power structures.

    International conflict also shaped the Late Middle Ages. One of the most famous series of wars was the Hundred Years’ War between the Kingdom of England and the Kingdom of France, which actually lasted, with interruptions, from 1337 to 1453. This long conflict involved not only battles and sieges but also complex questions of succession, allegiance, and national identity. New military technologies—such as the English longbow and, increasingly, gunpowder weapons like cannons—began to change the nature of warfare. Over time, the war contributed to the development of more centralized states and a stronger sense of “English” and “French” identity, even as it brought destruction to many regions and hardship to countless civilians.

    Despite—or in some cases because of—these crises, the Late Middle Ages was also a period of significant cultural and intellectual creativity. Vernacular literature continued to flourish: Geoffrey Chaucer in England, Giovanni Boccaccio in Italy, and many others wrote works that engaged with themes of love, morality, social satire, and the human response to disaster. In many regions, artists experimented with new techniques and more naturalistic styles, foreshadowing the Renaissance. Intellectual currents sometimes called “early humanism” began to focus more attention on the study of classical texts, the dignity and potential of human beings, and the complexities of worldly life. Meanwhile, religious life remained intense and varied, with popular devotional movements, mysticism, and renewed calls for reform within the Church. These developments laid important groundwork for the religious and intellectual transformations of the 15th and 16th centuries.

    Beyond Europe, other regions also underwent major changes during the Late Middle Ages. In East Asia, the Ming dynasty in China rose after the collapse of the Mongol-led Yuan dynasty. Ming rulers restored Han Chinese rule, strengthened the civil service examination system, and oversaw periods of economic growth and artistic brilliance. Chinese porcelain, painting, and literature flourished, and under the early Ming, maritime expeditions led by the admiral Zheng He projected Chinese presence into the Indian Ocean, reaching as far as East Africa. Elsewhere in Asia, powerful states and sultanates—from the Delhi Sultanate in India to various kingdoms in Southeast Asia—continued to shape regional politics, religion, and trade, connecting the Indian Ocean world into a vibrant network of exchange.

    Across the Atlantic, in the Americas, complex and sophisticated societies such as the Aztec Empire in Mesoamerica and the Inca Empire in the Andes reached impressive heights in the Late Middle Ages. The Aztecs built their capital at Tenochtitlan, a city of monumental temples, markets, and causeways, while the Inca constructed extensive road systems, terraces, and administrative centers across diverse landscapes. These empires developed intricate political structures, religious traditions, and artistic styles, and engaged in long-distance trade and diplomacy with neighboring peoples. Although they were not connected to Afro-Eurasian trade networks, their histories were equally rich and dynamic. By the late 15th century, however, European voyages of exploration—driven by new navigational technologies, economic ambitions, and religious motivations—would bring these worlds into increasingly direct and often violent contact.

    The Late Middle Ages, then, can be understood as an era of both crisis and creativity, disruption and adaptation. Famine, plague, and war challenged existing institutions, yet also opened space for social, economic, and intellectual change. New forms of political authority and identity began to emerge, as did new artistic and literary expressions that explored the depths of human experience. Across Africa, Europe, Asia, and the Americas, societies were confronting environmental pressures, technological changes, and shifting trade patterns in their own distinct ways. As this period drew to a close, the post-classical world was gradually giving way to what we often call the “early modern” era—marked by the Renaissance, the rise of powerful centralized states and empires such as the Ottoman Empire, Safavid Persia, and Mughal India, and the beginning of global oceanic exploration. Together, these changes set the stage for a new chapter in world history, one that would be profoundly interconnected, sometimes exploitative, and endlessly transformative.
    """
}
