//
//  ModernReadingText.swift
//  World History
//
//  Created by Christopher Endress on 5/27/23.
//

import Foundation

struct ModernReadingText {
    let modernText = """
    The dawn of the Modern Period is often associated with events like the fall of Constantinople in 1453, the spread of the printing press in Europe, and the first large-scale encounters between distant parts of the world. While historians debate the exact dates and definitions, this era roughly spans from the late 15th century into the early 20th century. It was a time of accelerating change: new technologies, shifting political systems, expanding empires, and growing connections between continents. Yet, the Modern Period was not shaped by Europe alone. Great empires in the Islamic world, powerful kingdoms in Africa, sophisticated states in Asia, and complex societies in the Americas all played crucial roles in shaping the world that emerged.
    
    This era saw an intensification of long-distance travel and maritime exploration, particularly by European kingdoms along the Atlantic coast. Building on navigational knowledge that had been developed over centuries in the Mediterranean, the Indian Ocean, and beyond—by Arab, Persian, African, Chinese, South Asian, and Polynesian sailors—European explorers sought new sea routes for trade, prestige, and religious expansion. When Christopher Columbus reached the Caribbean in 1492 and other explorers sailed around Africa to the Indian Ocean or across the Pacific, they helped create a truly global network of exchange. These voyages brought new crops, animals, and ideas to different continents, but they also unleashed conquest, disease, and the forced movement of millions of people, especially through the transatlantic slave trade. The “Age of Discovery” was therefore both an age of connection and an age of exploitation.
    
    In the east, the Ottoman Empire emerged as one of the most influential powers of the early modern world. At its height, it governed territories across parts of Europe, North Africa, and the Middle East, serving as a crossroads of cultures, languages, and religions. The transformation of Constantinople into Istanbul after 1453 symbolized both continuity and change: Byzantine churches, such as the Hagia Sophia, stood alongside new mosques, markets, and public buildings. To the east of the Ottomans, the Safavid Empire in Persia and the Mughal Empire in South Asia also shaped the political and cultural landscape. These Islamic empires patronized scholars, artists, and architects, and they helped preserve, develop, and transmit knowledge in fields such as medicine, astronomy, mathematics, and philosophy. Many of the ideas that later fueled European science and philosophy had earlier roots in the work of Muslim, Persian, Arab, and Central Asian scholars during the Islamic Golden Age and the centuries that followed.
    
    Around the same time, Europe experienced the Renaissance, a cultural movement that began in Italian city-states and gradually spread northward. Artists, writers, and thinkers turned with renewed interest to the classical heritage of ancient Greece and Rome, while also absorbing influences from Byzantine and Islamic scholarship that had preserved and commented on these texts. Renaissance thinkers emphasized human potential, curiosity, and critical inquiry, which shaped developments in art, architecture, literature, and education. Figures like Leonardo da Vinci and Michelangelo became symbols of this creative energy, but they were part of a much wider network of artisans, scholars, and patrons. The Renaissance is just one example of how societies across the world engaged in cycles of renewal and innovation, drawing on both local traditions and outside influences.
    
    The invention and spread of the printing press with movable type in Europe, often associated with Johannes Gutenberg in the mid-15th century, massively accelerated the circulation of ideas. Books, pamphlets, and later newspapers could be produced more quickly and cheaply than handwritten manuscripts, making it easier for information to reach wider audiences. It is important to note that printing technologies had existed earlier in places like China and Korea, where woodblock and movable metal type were already in use. In Europe, however, the printing press became deeply entwined with religious debate, scientific communication, and political controversy. As more people gained access to printed materials, literacy slowly increased, and a broader “reading public” emerged. These changes laid important foundations for modern education, journalism, and public debate.
    
    The 16th century also brought profound religious upheaval in Europe. The Protestant Reformation, sparked in part by Martin Luther’s criticisms of Church practices, fractured the religious unity of Western Christendom. New Protestant denominations emerged, while the Catholic Church launched its own internal reforms. These changes led to decades of conflict, alliances, and power struggles, as rulers used religious identity to strengthen their authority or challenge their rivals. At the same time, religious and philosophical developments were taking place elsewhere in the world: Islamic scholars debated law and theology in major centers of learning, Hindu, Sikh, Buddhist, and Confucian thinkers responded to changing social conditions, and Indigenous spiritual traditions in the Americas, Africa, and Oceania adapted to the pressures of colonialism and cultural contact. In many regions, faith, politics, and daily life were deeply intertwined.
    
    Alongside these religious and cultural shifts, new approaches to studying nature began to take shape in what is often called the Scientific Revolution. European thinkers such as Nicolaus Copernicus, Galileo Galilei, Johannes Kepler, and later Isaac Newton proposed models of the cosmos and laws of motion that challenged long-held beliefs. They emphasized observation, measurement, and experimentation as tools for understanding the world. Yet this transformation did not arise in isolation. Earlier work by scholars from the Islamic world, India, China, and other regions had preserved and expanded upon Greek and other traditions in astronomy, mathematics, and medicine, providing important foundations for later discoveries. New scientific ideas, in turn, influenced navigation, engineering, and agriculture, changing how people lived and worked.
    
    These multifaceted developments of the early Modern Period—expanding trade and exploration, powerful empires in both Europe and Asia, religious reformation, and new scientific inquiry—pushed the world into a more tightly connected and rapidly changing era. European powers began to gain military and economic advantages in some regions, but they coexisted with strong states in the Ottoman lands, Safavid Persia, Mughal India, Qing China, Tokugawa Japan, and numerous African kingdoms and Indigenous American societies. Rather than a simple story of one continent rising while others declined, the early Modern Period was a complex global tapestry, with many centers of power and creativity influencing one another through cooperation, competition, and conflict.
    
    As the Modern Period progressed into the 17th and 18th centuries, an intellectual and philosophical movement known as the Enlightenment took shape, especially in Europe and the Atlantic world. Associated with thinkers like Voltaire, Jean-Jacques Rousseau, John Locke, and Immanuel Kant, the Enlightenment emphasized reason, empirical evidence, and skepticism toward unquestioned authority. Philosophers discussed questions about human rights, the social contract, religious tolerance, and the role of governments. They debated how societies should be organized and what it meant to be free or equal. While many Enlightenment figures claimed to champion universal principles, their ideas were often limited by the social attitudes of their time and did not always extend fully to women, enslaved people, colonized populations, or non-European cultures. Still, their writings had a lasting influence on later political revolutions and human rights movements.
    
    During the same centuries, colonial empires dramatically expanded their reach. European powers—including Spain, Portugal, Britain, France, and the Netherlands—fought for control of trade routes, coastal forts, and inland territories across the Americas, Africa, and Asia. This expansion was driven by commerce, strategic rivalry, and a desire for resources such as silver, sugar, spices, cotton, and later rubber and minerals. The human cost of this expansion was enormous. Indigenous peoples across the Americas and other regions suffered from war, displacement, and devastating epidemics brought by new diseases. The transatlantic slave trade forced millions of Africans into brutal conditions on plantations and in mines, tearing families and communities apart. At the same time, enslaved people, Indigenous nations, and colonized communities resisted in countless ways—through revolts, negotiations, cultural preservation, and the creation of new blended traditions that mixed African, Indigenous, European, and Asian elements.
    
    In the 18th century, the early stages of the Industrial Revolution began to appear, first in parts of Great Britain and later in other regions. Innovations in textile production, such as the spinning jenny and the power loom, and in energy use, most famously the steam engine, transformed how goods were made. Factories began to concentrate workers, machines, and raw materials in specific locations, shifting many economies from rural, agricultural foundations toward urban, industrial ones. This transition did not happen all at once or everywhere at the same pace. In other parts of the world, craft production, local industries, and older trading systems remained central for a long time. Still, the changes in manufacturing and transportation in Britain and later in places like Western Europe, the United States, and Japan would eventually reshape global trade, labor, and the environment.
    
    Scientific and intellectual life also continued to evolve rapidly during this period. Isaac Newton’s laws of motion and universal gravitation provided a powerful framework for understanding physical phenomena, influencing everything from astronomy to engineering. Carl Linnaeus developed a system for classifying plants and animals that contributed to modern biology, even though later generations would revise and challenge some of his assumptions. Advances in chemistry, medicine, and geography expanded human knowledge of the natural world and the human body. At the same time, new scientific theories were sometimes used to justify imperialism or racial hierarchies, reminding us that knowledge can be shaped by the social and political contexts in which it is produced. Across the globe, scholars, travelers, and local experts exchanged information, sometimes as equal partners and sometimes under unequal, colonial conditions.
    
    Amidst these developments, the political landscape was undergoing dramatic changes. Enlightenment ideas about liberty, representation, and popular sovereignty helped inspire revolutions and reforms. In the late 18th century, the American Revolution led to the creation of a new republic in North America, founded on ideals of individual rights and constitutional government, even as slavery and the displacement of Indigenous peoples continued. Shortly afterward, the French Revolution challenged monarchy and aristocracy in Europe, unleashing waves of radical change, violence, and political experimentation. The Haitian Revolution, led by enslaved and formerly enslaved people in the French colony of Saint-Domingue, created the first Black republic and abolished slavery, powerfully demonstrating that the ideals of freedom and equality could be claimed by those whom colonial society had tried to deny. In the early 19th century, independence movements spread across Latin America, reshaping the map of the Americas.
    
    From the ideas that emerged during the Enlightenment to the sweeping societal transformations triggered by early industrialization and revolutions, the middle part of the Modern Period was marked by a whirlwind of change. Old hierarchies were questioned, new nations were formed, and debates over citizenship, rights, and equality intensified. At the same time, colonial empires adapted rather than disappeared, and many people remained excluded from the freedoms proclaimed in new constitutions. This tension between ideals and reality became one of the defining features of modern history, setting the stage for the struggles and achievements that would follow.
    
    The 19th and early 20th centuries, often seen as the final phase of the Modern Period, were a time of remarkable innovation and intense conflict. The Industrial Revolution entered a second phase, with new technologies such as railways, telegraphs, electricity, and later internal combustion engines transforming everyday life. Factories grew larger and more complex, producing steel, chemicals, and mass-produced goods that could be shipped around the world. Cities expanded rapidly as people moved from rural areas in search of work, creating crowded neighborhoods, new forms of poverty, and new opportunities for social mobility. Environmental change accelerated as forests were cleared, mines dug deeper, and pollution increased, leaving long-term marks on landscapes and climates.
    
    On the political front, nationalism became a powerful force. People in various regions began to see themselves as part of distinct nations with shared histories, languages, or cultures, and they sought states that reflected these identities. In Europe, this contributed to the unification of Italy and Germany in the late 19th century, changing the balance of power on the continent. In other parts of the world, nationalist movements emerged in response to colonial rule and foreign domination. In the Ottoman Empire, in India under British control, in parts of Africa and East Asia, reformers and activists debated how to preserve or recover autonomy while adopting or adapting aspects of modern technology and governance. Japan’s Meiji Restoration, for example, combined rapid industrialization and state-building with efforts to maintain a distinct cultural identity, turning the country into a major regional power.
    
    In the realm of thought, the Modern Period saw further seismic shifts. Charles Darwin’s theory of evolution through natural selection offered a new explanation for the diversity of life on Earth, challenging traditional interpretations and sparking intense debates about science and religion. Sigmund Freud’s exploration of the unconscious mind suggested that human behavior was shaped by hidden desires and internal conflicts, opening new paths in psychology and literature. Karl Marx’s analysis of capitalism and his vision of class struggle inspired labor movements and political revolutions, influencing debates about economic justice, inequality, and the role of the state. Alongside these well-known figures, many other thinkers—from feminist writers and religious reformers to Pan-African leaders and anti-colonial intellectuals—questioned existing systems and proposed alternative futures.
    
    The early 20th century brought a deadly escalation in global conflicts. Competition among industrialized powers, intertwined with nationalist ambitions and colonial rivalries, contributed to the outbreak of the First World War in 1914. New weapons and technologies, including machine guns, poison gas, tanks, and airplanes, turned the war into a catastrophic struggle that caused immense suffering and loss of life. The war led to the collapse or weakening of several empires, including the Austro-Hungarian, Ottoman, German, and Russian empires, and redrew political borders, particularly in Europe and the Middle East. In 1917, the Russian Revolution established a new kind of state based on communist ideology, which would go on to play a central role in 20th-century global politics. Many people hoped that international agreements after the war would bring lasting peace, but unresolved grievances and new inequalities remained.
    
    These final decades of the Modern Period were also marked by rapid change in art, culture, and communication. Artists experimented with new styles—such as impressionism, expressionism, and later abstraction and surrealism—to capture the speed, anxiety, and complexity of modern life. Writers and poets embraced modernism, playing with narrative structure, language, and perspective to reflect changing understandings of memory, identity, and time. New forms of mass media, including photography, recorded sound, and film, allowed images and stories to travel quickly across borders, shaping shared global experiences. At the same time, cultural exchanges were not always equal: colonial exhibitions, popular entertainment, and advertising often reflected and reinforced stereotypes, even as they brought distant cultures into everyday awareness.
    
    The Modern Period was thus an era of dramatic and often contradictory change—of scientific breakthroughs and industrial growth, but also of conquest, dispossession, and war; of powerful new ideas about rights and democracy, alongside systems of racial inequality, patriarchy, and imperial rule. Its legacies are visible in today’s political borders, economic systems, social movements, and cultural expressions. By viewing this period from a global and balanced perspective—acknowledging contributions from Europe, the Islamic world, Africa, the Americas, and Asia alike—we gain a deeper understanding of how interconnected our histories have always been. The Modern Period laid much of the groundwork for the contemporary world, and its unresolved questions about power, justice, and human dignity continue to shape our shared future.
    """
}
