//
//  Text.swift
//  World History
//
//  Created by Christopher Endress on 5/23/23.
//

import Foundation

struct ReadingText {
    let prehistoryText = """
    The story of our human ancestors begins in the hazy depths of prehistory, long before the invention of writing, in a time when our understanding of the past relies entirely on archaeological evidence. Prehistory stretches from the earliest tool-making hominins to the invention of writing systems in different parts of the world, a span of hundreds of thousands of years. Because there are no written records from this era, historians and scientists piece together the story from fossils, stone tools, cave paintings, DNA, and the remains of ancient settlements. It is an era that includes the evolution of Homo sapiens in Africa around 300,000 years ago, the spread of our species across every continent except Antarctica, and the gradual development of more complex ways of living. Across this immense timescale, humans learned to adapt to harsh climates, cooperate in larger groups, reshape landscapes, and eventually lay the foundations for the first cities and states.
    
    The journey often begins with the Paleolithic era, or Old Stone Age. This epoch, which stretches from about 2.6 million years ago until roughly 10,000 BCE, covers a time when human life was organized in small, mobile communities. People survived by hunting animals, gathering wild plants, and exploiting whatever resources each environment offered. While earlier explanations sometimes divided labor sharply—men as hunters and women as gatherers—archaeologists today recognize that roles likely varied greatly between groups, and that everyone’s contribution was crucial for survival. Over time, early humans developed increasingly sophisticated stone tools: from simple chipped rocks to carefully shaped hand axes, blades, and later, finely crafted points that could be attached to spears. These tools did more than just make hunting easier; they reflected growing intelligence, planning, and an ability to pass knowledge from one generation to the next. Language, though invisible in the archaeological record, almost certainly emerged during this time, allowing people to coordinate complex tasks, share stories, and strengthen social bonds.
    
    One of the most pivotal developments in our ancestors’ existence was the mastery of fire. Early control of fire may have begun more than a million years ago, though its regular and reliable use came later. Fire provided warmth in cold climates and protection from predators, making new regions of the world habitable. It transformed the way people ate: cooking food made it easier to chew and digest, allowing humans to gain more energy from the same resources. This may have had long-term effects on health, brain development, and population growth. Just as important, fire became a powerful social force. Evenings gathered around a hearth allowed people to extend their day into the night, tell stories, perform rituals, teach children, and resolve conflicts. In this way, firelight helped shape not only the physical environment, but also the inner world of human communities—their beliefs, emotions, and shared memories.
    
    Moving forward in time, during the last Ice Age, humans began to leave behind especially vivid evidence of their inner lives through art and ritual. Famous examples include the cave paintings of Lascaux in France and Altamira in Spain, where animals such as bison, horses, and deer are depicted with striking skill and imagination. But the artistic expression of prehistoric humans was not limited to Europe. Rock art and carvings have been found in Africa, Asia, Australia, and the Americas, each reflecting the local animals, symbols, and spiritual ideas of different groups. Small figurines, such as the so-called “Venus” statues, may have represented fertility, identity, or religious beliefs. Burials with grave goods—tools, ornaments, or even flowers—suggest that people cared deeply about the dead and may have believed in an afterlife or spiritual realm. Whether these artworks were part of hunting rituals, storytelling traditions, or religious ceremonies, they show that prehistoric humans were not just surviving; they were thinking symbolically, imagining unseen worlds, and seeking meaning in their lives.
    
    The end of the Paleolithic era coincided with the close of the last Ice Age, leading to major climate changes that reshaped ecosystems worldwide. Glaciers retreated, sea levels rose, and many large Ice Age animals either migrated or went extinct. This shift marked the dawn of the Mesolithic, or Middle Stone Age, a transitional period whose length varied greatly from region to region. As environments changed, so did human strategies for survival. In some areas, people created more specialized and refined stone tools, including tiny blades called microliths that could be set into wooden or bone handles to form arrows, sickles, and fishing gear. The appearance of harpoons, fishhooks, and boats in some regions reflects a growing reliance on rivers, lakes, and coasts. Rather than a single global transformation, this period saw a patchwork of adaptations: some groups became semi-sedentary, returning to the same seasonal camps year after year, while others remained highly mobile. What unites these different experiences is a pattern of innovation and experimentation in response to a warming world.
    
    This changing climate and the new strategies that emerged set the stage for one of the most profound shifts in human history: the gradual transition from a nomadic, hunter-gatherer lifestyle to more settled, agriculture-based communities. This shift did not happen overnight, nor did it occur everywhere at the same time. In some regions, people lived for thousands of years in mixed economies, combining wild resources with early forms of cultivation. In others, hunting and gathering remained a successful way of life long after farming had begun elsewhere. Still, over many generations, more and more groups experimented with planting seeds, tending crops, and managing herds. The results would eventually reshape human societies, landscapes, and relationships to the natural world.
    
    The Neolithic Revolution, or New Stone Age, refers to this broad transformation towards farming and settled life, although many historians now describe it as a slow evolution rather than a sudden “revolution.” Beginning around 10,000 BCE in some parts of the world and continuing until the development of writing, the Neolithic era saw major changes in technology, social organization, and belief systems. As people learned to cultivate plants and domesticate animals, they altered their environments more dramatically than ever before—clearing forests, building permanent structures, and reshaping rivers and fields. This new way of life brought both opportunities and risks. On one hand, farming could support larger, more stable populations; on the other, it bound communities more tightly to the success or failure of their crops and herds. The Neolithic era, therefore, is a story of ingenuity, experimentation, and adaptation as humans negotiated the benefits and costs of a newly settled existence.
    
    In the Fertile Crescent, an arc of land in the Middle East spanning parts of modern-day Iraq, Syria, Lebanon, Israel, Palestine, Jordan, Egypt, and regions of Turkey and Iran, people were among the first to experiment systematically with farming. They began to domesticate wild grains like barley and wheat, selecting plants with traits that made them easier to harvest, store, and replant. Over many generations, this careful selection turned wild grasses into true crops. At the same time, animals such as goats, sheep, pigs, and cattle were gradually domesticated, providing meat, milk, hides, and labor. This region is often highlighted in history because of the rich archaeological evidence it has left behind, but it was not the only cradle of agriculture. Independent centers of domestication also emerged in places such as the Yellow River and Yangtze River valleys in China, the highlands of New Guinea, parts of sub-Saharan Africa, and the Americas, where people domesticated crops like maize, potatoes, and squash. Together, these developments show that farming was a global innovation, arising from many different communities responding creatively to their environments.
    
    The shift to agriculture allowed many human groups to stay in one place for much longer periods of time, leading to the establishment of some of the world’s earliest villages. Sites such as Jericho in the West Bank and Çatalhöyük in modern-day Turkey provide a glimpse into these early settled communities. In Jericho, archaeologists have found evidence of stone walls and towers, suggesting organized labor and a concern for defense or flood control. At Çatalhöyük, houses were built so closely together that people likely entered through roofs, and interior walls were decorated with paintings and reliefs. These settlements contained storage areas for grain, spaces for communal gatherings, and areas that may have served religious or ceremonial purposes. Yet even as some communities became more sedentary, others maintained mobile or semi-mobile lifestyles, demonstrating that there was no single “correct” way to live during this time. Human societies experimented with a spectrum of possibilities, from small farming hamlets to larger, densely populated villages.
    
    The rise of agriculture led to a significant increase in the human population. With more reliable food sources, families could raise more children, and communities grew in size and complexity. This growth, however, brought new challenges. Farming demanded long hours of physically intensive labor, from plowing and planting to weeding and harvesting. A diet based heavily on a few staple crops could lead to nutritional deficiencies, even as it made famine less frequent in good years. Close contact with domesticated animals and denser living conditions made it easier for diseases to spread. Periods of drought, floods, or crop failure could threaten entire communities. At the same time, growing populations meant more competition for land and resources, sometimes leading to conflict. Prehistory, therefore, should not be imagined as a peaceful Eden; it was a dynamic and sometimes unstable world in which people had to constantly adapt to new pressures.
    
    Despite these challenges, the advantages of farming and settled life gradually became clear for many societies. Surplus food—grain stored in clay jars, baskets, or granaries—freed some individuals from the daily work of producing food. This allowed them to specialize in other tasks: crafting pottery, weaving textiles, knapping advanced tools, building structures, or developing new forms of religious and political leadership. Over time, this specialization helped create more layered social structures. Certain families or groups might control key resources, while others gained influence as spiritual leaders, skilled artisans, or successful traders. Systems of cooperation and hierarchy emerged, along with the first hints of social inequality. Trade networks expanded as communities exchanged obsidian, shells, pigments, and other valuable goods across long distances. Alongside these material changes, new myths, rituals, and symbols developed to explain the world, legitimize authority, and bind communities together.
    
    Toward the end of the Neolithic era, a new material began to reshape human societies: metal. At first, people worked with naturally occurring metals like native copper and gold, hammering them into simple ornaments or tools. Gradually, they discovered that heating certain types of rock in hot fires produced molten metal that could be poured into molds. This knowledge opened up an entirely new technological frontier. Metalworking required specialized skills, control over high-temperature fires, and access to specific ores, often found far from major settlements. As a result, early metalworkers were highly valued, and control of metal resources could become a source of power and prestige. The spread of metallurgy marked a transition from a world in which stone tools dominated to one in which metal tools and weapons offered new possibilities—and new forms of inequality and conflict.
    
    The development of metallurgy, especially the creation of bronze—an alloy typically made by combining copper with tin—had far-reaching effects on human societies. Bronze is harder and more durable than pure copper or most stone, making it ideal for tools, weapons, and decorative objects. Communities that mastered bronze production could craft axes, knives, chisels, spearheads, and swords that outperformed older tools in both war and daily work. Producing bronze, however, required the coordination of miners, smelters, smiths, and traders, because copper and tin deposits were rarely found in the same place. This complexity encouraged the growth of long-distance trade and deeper forms of social organization. Rulers, elites, or temple institutions often controlled access to metal, reinforcing their authority and reshaping economic and political life.
    
    Early societies soon realized that metal tools could transform not just warfare, but also agriculture, construction, and crafts. Bronze plowshares, for example, could cut more deeply into the soil than wooden ones, improving the productivity of fields. Stronger axes allowed people to clear forests more quickly, making way for farmland and settlements—but also contributing to deforestation and soil erosion in some regions. Metal chisels and adzes improved woodworking, enabling the construction of larger buildings, boats, and vehicles. In the hands of skilled artisans, bronze became a medium for intricate jewelry, religious icons, and ceremonial objects that expressed the values and beliefs of different cultures. Metal, in short, magnified both the creative and destructive capacities of human societies.
    
    One of the most momentous technological advances of the late Neolithic and early Bronze Age periods was the invention and spread of the wheel, along with new forms of transport and agricultural equipment such as the plow. Wheeled vehicles—carts and wagons drawn by animals like oxen, donkeys, or horses—made it possible to move goods and people over longer distances with less effort. This greatly expanded trade networks, linking distant regions and allowing ideas, technologies, and cultural practices to travel more quickly. At the same time, improvements to the plow increased the amount of land that could be farmed and the depth to which soil could be turned, enhancing yields in many regions. These innovations fundamentally changed how communities related to space and distance: journeys that once took many days on foot could now be completed more efficiently with wheeled transport, contributing to tighter regional connections and more complex economic systems.
    
    The surplus of resources generated by improved farming methods, metallurgy, and trade laid the groundwork for the rise of the first cities. In different regions of the world, dense urban centers emerged: Uruk and Ur in Mesopotamia, early cities of the Indus Valley such as Harappa and Mohenjo-Daro, and important settlements along the Nile in Egypt, among others. These cities featured crowded neighborhoods, marketplaces, temples, and administrative buildings. They required new forms of leadership, record-keeping, and conflict resolution to manage water systems, allocate land, organize labor, and maintain social order. Urban life brought people from different backgrounds together, fostering innovation in crafts, architecture, music, and religious practice. It also intensified problems such as inequality, disease, and competition over resources. At the same time, many communities outside the cities continued to live in villages or pastoral groups, reminding us that early urban civilizations existed alongside a wide variety of other ways of life.
    
    It was also during this broader period that writing was invented in several parts of the world, marking the transition from prehistory to history. In Mesopotamia, scribes developed cuneiform, a writing system made of wedge-shaped impressions pressed into clay tablets, around the fourth millennium BCE. In the Nile valley, Egyptian scribes and artists created hieroglyphics, a system that combined pictures with more abstract signs to represent sounds and ideas. Other early writing systems appeared later in places such as the Indus Valley and ancient China, each adapted to local languages and needs. Writing did not instantly replace older forms of communication; oral storytelling, memory, and performance remained crucial in every society. Still, the ability to fix words in lasting form transformed how information could be stored, shared, and controlled, opening the door to more complex legal systems, bureaucracies, and literary traditions.
    
    Cuneiform and other early scripts were used to record a wide range of information. Administrators used them to track harvests, taxes, and trade agreements, ensuring that goods and labor could be organized across growing territories. Rulers and religious authorities inscribed laws, decrees, hymns, and myths on clay tablets or stone monuments, presenting themselves as guardians of order and justice. Over time, writing also became a vehicle for storytelling, philosophy, and reflection on the human condition. Works like the Epic of Gilgamesh explore themes of friendship, mortality, and the search for meaning that still resonate today. It is important to remember, however, that written records reflect the perspectives of those who had access to literacy—often elites or specialists—while the voices of farmers, laborers, and many others remain largely silent. At the same time, many sophisticated societies left few or no written records at all, reminding us that complexity and creativity do not depend solely on writing.
    
    Towards the end of the Bronze Age, around 1200 BCE in the eastern Mediterranean and Near East, a series of crises led to the disruption or collapse of many powerful states. The reasons for this widespread upheaval are still debated. Possible factors include climate change, drought, internal rebellions, shifts in trade routes, invasions or migrations by new groups, and the growing cost of maintaining large armies and palaces. Whatever the causes, cities were destroyed or abandoned, ruling dynasties fell, and many long-standing political systems were transformed. This period of instability was not simply an ending; it also cleared the way for new powers and new forms of social organization that would emerge in the subsequent Iron Age. In other parts of the world, different timelines and paths unfolded, but everywhere, communities continued to adapt to new technologies, environments, and challenges.
    
    As we conclude our journey through prehistory, we stand at the threshold of recorded history, looking ahead to the rise of the great civilizations of the ancient world. From the first tool-making hominins of the Paleolithic, through the artistic and spiritual expressions of Ice Age hunters, the experiments of early farmers, the growth of villages and cities, and the breakthroughs of metallurgy and writing, the story of prehistory is not a simple tale of steady, linear progress. Instead, it is a complex, global mosaic of different societies, each responding in its own way to the opportunities and constraints of its environment. What unites these many threads is a shared human capacity for creativity, cooperation, and resilience. Understanding this deep past helps us see that the roots of our modern world stretch far beyond any single region, culture, or tradition, and that the story of humanity has always been diverse, interconnected, and evolving.
    """
}
